exports.getBalance = require("./simple-coin/get-balance")
exports.getAddress = require("./get-address")
exports.sendCoin = require("./simple-coin/send-coin")
exports.getIndexBalance = require("./index-coin/get-index-balance")
exports.sendIndexCoin = require("./index-coin/send-index-coin")
exports.createIndex = require("./index-coin/create-index")